spring:
  application:
    name: template-zuul
  profiles:
    active: native
  cloud:
    config:
      #      配置服务中心的网址
      uri: http://locahost:8888
      #      配置文件的前缀名
      name: application-zuul
      #      配置文件的环境标识 dev: 开发环境 test: 测试环境 prod: 生产环境
      profile: dev
  #      配置仓库的分支。如果是本地读取，可不配置
  #      label:
  boot:
    admin:
      client:
        url: http://localhost:9004